### PR TITLE
Update CWL links #2

### PR DESCRIPTION
**Pull request by mr-c**
Current version is v1.0

### CODE REVIEW

**Comment by BoPeng** [comment]
Thanks. SoS takes a vastly different approach from CWL. Hopefully our evaluation of CWL is not way off.

**Comment by mr-c** [comment]
@BoPeng Thanks for the merge.

I have different perspectives than what is stated here -- I should probably write a blog post on it.

Cheers,

**Comment by BoPeng** [comment]
If you read a bit more about SoS (start from [this presentations](http://vatlab.github.io/SOS/doc/presentations/SoS_BCB_Jan23_2017/index.html)?), you would notice a strong emphasis on day-to-day interactive work, light-weight and readable workflow, easy for sharing and modification ... It is not designed to be as rigorous and as powerful as CWL, even not a workflow system in the conventional sense (interactive use, run most steps internally and execute some tasks on [remote hosts/queues](http://vatlab.github.io/SOS/doc/tutorials/Remote_Execution.html)). I would be very interested to read your perspectives on SoS.

**Comment by mr-c** [comment]
Hello @BoPeng, I opened another issue to request clarification about what CWL is and isn't at https://github.com/vatlab/sos-docs/issues/14

Cheers,

**Pull request merged**
